/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sparkTest

import sparkTest.usecases.InsertDataInStoreUseCase

fun main() {
    val useCase = InsertDataInStoreUseCase()
    useCase.execute()
}
