/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sparkTest

import org.apache.spark.sql.SparkSession
import sparkTest.entity.TableNameEntity
import java.util.*

fun main() {
//    val sparkConf = SparkConf()
//    sparkConf.setAppName("sparkTest")
//
//    val sparkContext = SparkContext(sparkConf)
    val session = SparkSession.builder()
        .appName("sparkTest")
        .getOrCreate()

//    val dataFrame = session.read()
//        .format("jdbc")
//        .option("url", "jdbc:postgresql://localhost:5432/sparktest")
//        .option("dbtable", "public.table_name")
//        .option("user", "postgres")
//        .option("password", "postgres")
//        .load()

    val rows = generateSequence(0) { it + 1 }
        .take(10000)
        .toList()
        .map {
            TableNameEntity(
                UUID.randomUUID(),
                UUID.randomUUID().toString(),
                it
            )
        }
    val frameToWrite = session.createDataFrame(rows, TableNameEntity::class.java)
    frameToWrite.write()
        .format("jdbc")
        .option("url", "jdbc:postgresql://localhost:5432/sparktest")
        .option("dbtable", "public.table_name")
        .option("user", "postgres")
        .option("password", "postgres")
        .save()
}
